In [2]:
import torch
import torch.nn as nn

In [203]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        
        # channels, outputs, kernel size
        self.conv1 = nn.Conv2d(1, 6, 3)
        
    def forward(self, x):
        x = nn.functional.max_pool2d(self.conv1(x), 2)
        return x

In [204]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
)


In [195]:
# data size, channels, width, height
x = torch.randn(1, 1, 4, 4)
print(x)

tensor([[[[ 2.2723,  0.7360, -1.0862, -0.4872],
          [-0.6404,  1.2158, -0.0180,  0.6721],
          [ 1.7041,  0.5297, -0.6341,  1.2048],
          [ 0.4320,  1.0316, -0.5279,  1.0496]]]])


In [196]:
y = net(x)
print(y)

tensor([[[[0.5817]],

         [[0.8719]],

         [[0.5079]],

         [[0.9054]],

         [[1.2656]],

         [[0.8614]]]], grad_fn=<MaxPool2DWithIndicesBackward>)


In [198]:
params = list(net.parameters())
w = params[0].data
b = params[1].data
print(w)
print(b)

tensor([[[[-0.0323,  0.1901, -0.1195],
          [ 0.2449,  0.0633,  0.2411],
          [-0.0289, -0.1152, -0.2723]]],


        [[[ 0.1113,  0.3040,  0.2943],
          [-0.2375, -0.1952, -0.1652],
          [ 0.2797,  0.0815, -0.0654]]],


        [[[ 0.0887,  0.0333,  0.0238],
          [ 0.3057, -0.3195,  0.0487],
          [-0.0994, -0.0628, -0.0315]]],


        [[[-0.1506, -0.0827, -0.1844],
          [ 0.3236,  0.0587,  0.0735],
          [ 0.2438,  0.2397, -0.0852]]],


        [[[ 0.3044, -0.3202,  0.1390],
          [-0.0546, -0.2390,  0.3233],
          [ 0.3001,  0.3214, -0.0320]]],


        [[[ 0.1630,  0.1174,  0.1217],
          [ 0.2168, -0.0438, -0.1957],
          [ 0.0637,  0.3061,  0.3132]]]])
tensor([ 0.0173,  0.2360,  0.0640, -0.0272,  0.1779,  0.1770])
