In [1]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# conv1: 1x32x32 -> 6x28x28 -> 6x14x14
# conv2: 6x14x14 -> 16x10x10 -> 16x5x5

In [88]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # channel, output, kernel size
        self.conv1 = nn.Conv2d(2, 3, 3)
        
    def forward(self, x):
        x = self.conv1(x)
        return x

In [89]:
net = Net()

In [90]:
params = list(net.parameters())

In [91]:
W = params[0].data
b = params[1].data

In [94]:
x = torch.randn(1, 2, 4, 4)
print(x)

tensor([[[[ 0.0685,  1.0146, -0.5947, -2.6103],
          [ 0.6408, -0.2963,  0.0708, -1.1136],
          [-0.2098,  0.4360,  0.1099,  0.2932],
          [ 1.3618,  0.4192,  1.3655,  1.5763]],

         [[-1.8189,  0.0711, -0.1404,  0.2551],
          [ 1.0315, -0.0242,  0.6710, -0.6647],
          [-1.3335,  0.1867, -0.8789,  0.1255],
          [ 0.5127, -1.5153, -0.4695, -0.1922]]]])


In [133]:
print(W[0])

tensor([[[-0.1287,  0.0793,  0.1840],
         [ 0.1554,  0.1311, -0.2082],
         [ 0.1343,  0.1298,  0.0986]],

        [[-0.0169,  0.1697,  0.0251],
         [ 0.1106, -0.1572,  0.0230],
         [-0.0995, -0.0036,  0.1832]]])


In [95]:
y = net(x)
print(y)

tensor([[[[ 0.0088, -0.6781],
          [-0.2349,  0.4431]],

         [[ 0.8282,  0.1840],
          [ 0.2981,  0.5483]],

         [[ 0.4871,  0.2354],
          [-0.5766, -0.4405]]]], grad_fn=<ThnnConv2DBackward>)


In [138]:
W[0][1]*x[0][1][:3, :3]

tensor([[ 0.0307,  0.0121, -0.0035],
        [ 0.1141,  0.0038,  0.0154],
        [ 0.1326, -0.0007, -0.1610]])

In [152]:
print(torch.sum(W[0][0]*x[0][0][:3, :3]) + torch.sum(W[0][1]*x[0][1][:3, :3]) + b[0])
print(torch.sum(W[0][0]*x[0][0][:3, 1:]) + torch.sum(W[0][1]*x[0][1][:3, 1:]) + b[0])
print(torch.sum(W[0][0]*x[0][0][1:, :3]) + torch.sum(W[0][1]*x[0][1][1:, :3]) + b[0])
print(torch.sum(W[0][0]*x[0][0][1:, 1:]) + torch.sum(W[0][1]*x[0][1][1:, 1:]) + b[0])

tensor(0.0088)
tensor(-0.6781)
tensor(-0.2349)
tensor(0.4431)
