In [48]:
import torch
import torch.nn as nn


In [114]:
class Model(nn.Module):
    
    def __init__(self):
        super(Model, self).__init__()
        self.fc = nn.Linear(5, 3)
        
    def forward(self, x):
        x = self.fc(x)
        #x = torch.relu(x)
        #x = torch.sigmoid(x)
        x = torch.tanh(x)
        return x

In [115]:
model = Model()
x = torch.randn(5)

In [116]:
print(x)

tensor([-0.0600, -0.7297,  0.0449, -0.3245,  0.8764])


In [117]:
y = model(x)
print(y)

tensor([0.4839, 0.3266, 0.6011], grad_fn=<TanhBackward>)


In [118]:
params = list(model.parameters())
print(params)

[Parameter containing:
tensor([[-0.0248, -0.4236, -0.1278,  0.1284,  0.3196],
        [-0.2035, -0.2223, -0.1443, -0.3174,  0.0635],
        [-0.1202,  0.0036, -0.3932, -0.3987,  0.3035]], requires_grad=True), Parameter containing:
tensor([-0.0152,  0.0125,  0.3127], requires_grad=True)]


In [119]:
w = params[0].data
b = params[1].data
print(w)
print(b)

tensor([[-0.0248, -0.4236, -0.1278,  0.1284,  0.3196],
        [-0.2035, -0.2223, -0.1443, -0.3174,  0.0635],
        [-0.1202,  0.0036, -0.3932, -0.3987,  0.3035]])
tensor([-0.0152,  0.0125,  0.3127])


In [126]:
yhat = w@x+b
print(y)
print(yhat)
print(F.relu(yhat))
print(1/(1+torch.exp(-yhat)))
print((torch.exp(2*yhat)-1)/(torch.exp(2*yhat)+1))
print(2/(1+torch.exp(-2*yhat))-1)

tensor([0.4839, 0.3266, 0.6011], grad_fn=<TanhBackward>)
tensor([0.5281, 0.3390, 0.6949])
tensor([0.5281, 0.3390, 0.6949])
tensor([0.6290, 0.5839, 0.6671])
tensor([0.4839, 0.3266, 0.6011])
tensor([0.4839, 0.3266, 0.6011])
