In [1]:
import tensorflow as tf
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 1. 연습1

In [2]:
hello = tf.constant('Hello, TensorFlow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [4]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a,b,c]))
sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [6]:
x_data = [[1,2,3],[4,5,6]]

In [7]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2]))

In [8]:
W = tf.Variable([[0.1, 0.1], [0.2, 0.2], [0.3, 0.3]])

In [9]:
expr = tf.matmul(X, W) + b

In [10]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(x_data)
print(sess.run(W))
print(sess.run(b))
print(sess.run(expr, feed_dict={X: x_data}))
sess.close()

[[1, 2, 3], [4, 5, 6]]
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
[-0.41599578  0.823621  ]
[[0.9840043 2.2236211]
 [2.7840042 4.023621 ]]


In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(x_data)
    print(sess.run(W))
    print(sess.run(b))
    print(sess.run(expr, feed_dict={X: x_data}))

[[1, 2, 3], [4, 5, 6]]
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
[ 1.0932581 -1.3807714]
[[2.4932582 0.0192287]
 [4.293258  1.8192286]]


#### 2. 연습2

In [12]:
x_data = [1,2,3]
y_data = [1,2,3]

In [54]:
W = tf.Variable(tf.random_uniform([1], -1., 1.))
b = tf.Variable(tf.random_uniform([1], -1., 1.))
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

hypothesis = W*X + b
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [102]:
(0.5832546*np.array([1,2,3]) + 0.2601378 - np.array([1,2,3]))**2

array([0.02452594, 0.32873366, 0.98029484])

In [98]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(b))
    print(sess.run(tf.square(hypothesis - Y), feed_dict={X: x_data, Y: y_data}))
    print(sess.run(hypothesis, feed_dict={X: x_data}))
    print(sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    print(sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data}))
    print('='*10)
    print(sess.run(W))
    print(sess.run(b))
    print(sess.run(cost, feed_dict={X: x_data, Y: y_data}))

[0.5832546]
[0.2601378]
[0.02452595 0.3287337  0.980295  ]
[0.8433924 1.426647  2.0099015]
0.4445182
[None, 0.4445182]
[0.8681619]
[0.3748084]
0.023937894


In [83]:
y_pred = 0.8724041*np.array([1,2,3])-0.48521328
y = np.array([1,2,3])
cost_1 = np.mean((y_pred-y)**2)
print(y_pred, y, cost_1)
y_pred_2 = 1.185579*np.array([1,2,3])-0.33713228
cost_2 = np.mean((y_pred_2-y)**2)
print(y_pred_2, y, cost_2)

[0.38719082 1.25959492 2.13199902] [1 2 3] 0.5590534916210128
[0.84844672 2.03402572 3.21960472] [1 2 3] 0.024117459782185074


In [97]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # 여기서 출력되는 cost는 optimization 실행 후의 cost임
    # 같이 실행([train_op, cost])하면 optimization 실행 전의 cost가 출력된
    for step in range(1001):
        #sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        sess.run(train_op, feed_dict={X: x_data, Y: y_data})
        cost_val = sess.run(cost, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, cost_val, sess.run(W), sess.run(b))
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))        
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))        

0 0.030397266 [0.79189765] [0.45527124]
100 0.00023184984 [0.9823152] [0.04020179]
200 1.7851129e-06 [0.99844825] [0.00352758]
300 1.3738865e-08 [0.99986386] [0.00030952]
400 1.0554402e-10 [0.999988] [2.716525e-05]
500 9.284425e-13 [0.999999] [2.3935595e-06]
600 2.3684757e-14 [0.9999999] [2.875297e-07]
700 0.0 [1.] [5.7058315e-08]
800 0.0 [1.] [5.7058315e-08]
900 0.0 [1.] [5.7058315e-08]
1000 0.0 [1.] [5.7058315e-08]
X: 5, Y: [5.]
X: 2.5, Y: [2.5]


#### 3. 연습3

In [104]:
# [털, 날개]
x_data = np.array([[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
y_data = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,0,0],
    [1,0,0],
    [0,0,1]
])

In [188]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W = tf.Variable(tf.random_uniform([2,3],-1,1))
b = tf.Variable(tf.zeros([3]))
L = tf.nn.relu(tf.matmul(X,W)+b)
model = tf.nn.softmax(L)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)
init = tf.global_variables_initializer()

In [198]:
with tf.Session() as sess:
    sess.run(init)
    for step in range(1000):
        sess.run(train_op, feed_dict={X: x_data, Y: y_data})
        if (step+1)%100 == 0:
            print(step+1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))  
            
    prediction = tf.argmax(model, axis=1)
    target = tf.argmax(Y, axis=1)
    print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
    print('실제값:', sess.run(target, feed_dict={Y: y_data}))
    is_correct = tf.equal(prediction, target)
    accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
    print('정확도: {:.2f}%'.format(sess.run(accuracy*100, feed_dict={X: x_data, Y: y_data})))

100 1.1844134
200 1.1413332
300 1.1103493
400 1.0992799
500 1.0917565
600 1.0847609
700 1.0781925
800 1.0719794
900 1.0660701
1000 1.0604271
예측값: [0 1 1 0 0 0]
실제값: [0 1 2 0 0 2]
정확도: 66.67%


In [206]:
a = np.array([0, 1, 1, 0, 0, 0])
b = np.array([0, 1, 2, 0, 0, 2])
c = (a == b).astype(np.float32)
np.mean(c)

0.6666667

In [145]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(X, feed_dict={X: x_data}))
    print(sess.run(Y, feed_dict={Y: y_data}))
    print('='*40)
    print(sess.run(W))
    print(sess.run(b))
    print('='*40)
    print(sess.run(tf.matmul(X,W)+b, feed_dict={X: x_data}))
    print(sess.run(L, feed_dict={X: x_data}))
    print('='*40)
    print(sess.run(model, feed_dict={X: x_data}))
    print(sess.run(cost, feed_dict={X: x_data, Y: y_data}))

[[0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[ 0.23982978 -0.8846631   0.32417893]
 [ 0.10176492 -0.3515582   0.16995478]]
[0. 0. 0.]
[[ 0.          0.          0.        ]
 [ 0.23982978 -0.8846631   0.32417893]
 [ 0.3415947  -1.2362213   0.4941337 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.10176492 -0.3515582   0.16995478]]
[[0.         0.         0.        ]
 [0.23982978 0.         0.32417893]
 [0.3415947  0.         0.4941337 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.10176492 0.         0.16995478]]
[[0.33333334 0.33333334 0.33333334]
 [0.34785387 0.27367812 0.37846804]
 [0.34777477 0.24714135 0.40508386]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33626893 0.3037322  0.35999894]]
1.0861591


In [194]:
x = np.array([[0., 0.],
              [1., 0.],
              [1., 1.],
              [0., 0.],
              [0., 0.],
              [0., 1.]])
y = np.array([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.],
              [1., 0., 0.],
              [1., 0., 0.],
              [0., 0., 1.]])
w = np.array([[ 0.23982978, -0.8846631,   0.32417893],
              [ 0.10176492, -0.3515582,   0.16995478]])
z = np.matmul(x,w)+np.array([0,0,0])
l = np.fmax(z,0)
sm = np.exp(l)/np.sum(np.exp(l), axis=1).reshape((6,1))
loss = np.mean(-np.sum(y*np.log(sm), axis=1))
arg = np.argmax(sm, axis=1)
print(z)
print(l)
print(sm)
print(loss)
print(arg)

[[ 0.          0.          0.        ]
 [ 0.23982978 -0.8846631   0.32417893]
 [ 0.3415947  -1.2362213   0.49413371]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.10176492 -0.3515582   0.16995478]]
[[0.         0.         0.        ]
 [0.23982978 0.         0.32417893]
 [0.3415947  0.         0.49413371]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.10176492 0.         0.16995478]]
[[0.33333333 0.33333333 0.33333333]
 [0.34785386 0.27367812 0.37846803]
 [0.34777479 0.24714134 0.40508387]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33626892 0.30373216 0.35999892]]
1.0861591457342197
[0 2 2 0 0 2]


#### 4. 연습4

In [254]:
x_data = np.array([[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
y_data = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,0,0],
    [1,0,0],
    [0,0,1]
])

n = 4
X = tf.placeholder(tf.float32)
W1 = tf.Variable(tf.random_uniform([2,n], -1,1))
W2 = tf.Variable(tf.random_uniform([n,3], -1,1))
b1 = tf.Variable(tf.zeros([n]))
b2 = tf.Variable(tf.zeros([3]))

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
# 출력층에서는 활성화 함수를 잘 안 쓴다고 함
L2 = tf.matmul(L1, W2) + b2
model = tf.nn.softmax(L2, axis=1)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model), axis=1))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)
init = tf.global_variables_initializer()

In [255]:
with tf.Session() as sess:
    sess.run(init)
    for step in range(10000):
        sess.run(train_op, feed_dict={X: x_data, Y: y_data})
        if (1+step)%1000 == 0:
            print(1+step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    
    prediction = tf.argmax(model, axis=1)
    actual = tf.argmax(Y, axis=1)
    print("예측값:", sess.run(prediction, feed_dict={X: x_data}))
    print("실제값:", sess.run(actual, feed_dict={Y: y_data}))
    
    is_correct = tf.equal(prediction, actual)
    accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
    
    print('결과:', sess.run(is_correct, feed_dict={X: x_data, Y: y_data}))
    print('정확도: {:.2f}%'.format(sess.run(accuracy*100, feed_dict={X: x_data, Y: y_data})))
    print(sess.run(W1))
    print(sess.run(W2))
    print(sess.run(b1))
    print(sess.run(b2))

1000 0.00059554237
2000 0.00014022145
3000 5.4599626e-05
4000 2.5590656e-05
5000 1.3053522e-05
6000 6.993642e-06
7000 3.8941794e-06
8000 2.1855067e-06
9000 1.1920938e-06
10000 6.7551963e-07
예측값: [0 1 2 0 0 2]
실제값: [0 1 2 0 0 2]
결과: [ True  True  True  True  True  True]
정확도: 100.00%
[[ 1.7704268  -0.764212    3.6195383  -0.545701  ]
 [ 2.7818518  -2.88417    -2.5682533  -0.12653112]]
[[-2.6798215  -1.204446    2.974438  ]
 [ 2.6897655  -1.4241432  -3.102268  ]
 [-3.0831718   3.261634   -2.458045  ]
 [ 0.527411    0.9228296  -0.09494901]]
[2.5950307e-01 2.8841219e+00 3.4415956e-07 0.0000000e+00]
[ 1.333947  -1.6760839 -0.6542709]


#### 5. 연습5

In [2]:
data = np.loadtxt('./data.csv', delimiter=',', dtype=np.float32, unpack=True)

In [3]:
x_data = np.transpose(data[:2])
y_data = np.transpose(data[2:])

In [4]:
global_step = tf.Variable(0, trainable=False, name='global_step')

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2,10], -1,1))
b1 = tf.Variable(tf.zeros([10]))
L1 = tf.nn.relu(tf.matmul(X,W1)+b1)

W2 = tf.Variable(tf.random_uniform([10,20], -1,1))
b2 = tf.Variable(tf.zeros([20]))
L2 = tf.nn.relu(tf.matmul(L1,W2)+b2)

W3 = tf.Variable(tf.random_uniform([20,3], -1,1))
b3 = tf.Variable(tf.zeros([3]))
model = tf.nn.softmax(tf.matmul(L2,W3)+b3, axis=1)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model), axis=1))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost, global_step=global_step)
init = tf.global_variables_initializer()

In [6]:
saver = tf.train.Saver(tf.global_variables())
ckpt = tf.train.get_checkpoint_state('./model')

with tf.Session() as sess:
    if ckpt and tf.train.checkpoint_exists(ckpt.model_checkpoint_path):
        saver.restore(sess, ckpt.model_checkpoint_path)
    else:
        sess.run(init)
        
    for step in range(100):
        sess.run(train_op, feed_dict={X: x_data, Y: y_data})
        print('Step: {}, Cost: {:.3f}'.format(sess.run(global_step), sess.run(cost, feed_dict={X: x_data, Y: y_data})))
            
    saver.save(sess, './model/cnn.ckpt', global_step=global_step)

Step: 1, Cost: 1.953
Step: 2, Cost: 1.666
Step: 3, Cost: 1.422
Step: 4, Cost: 1.225
Step: 5, Cost: 1.075
Step: 6, Cost: 0.967
Step: 7, Cost: 0.888
Step: 8, Cost: 0.830
Step: 9, Cost: 0.780
Step: 10, Cost: 0.737
Step: 11, Cost: 0.697
Step: 12, Cost: 0.667
Step: 13, Cost: 0.641
Step: 14, Cost: 0.618
Step: 15, Cost: 0.598
Step: 16, Cost: 0.580
Step: 17, Cost: 0.564
Step: 18, Cost: 0.550
Step: 19, Cost: 0.535
Step: 20, Cost: 0.522
Step: 21, Cost: 0.511
Step: 22, Cost: 0.501
Step: 23, Cost: 0.492
Step: 24, Cost: 0.483
Step: 25, Cost: 0.474
Step: 26, Cost: 0.466
Step: 27, Cost: 0.458
Step: 28, Cost: 0.450
Step: 29, Cost: 0.442
Step: 30, Cost: 0.435
Step: 31, Cost: 0.428
Step: 32, Cost: 0.421
Step: 33, Cost: 0.414
Step: 34, Cost: 0.407
Step: 35, Cost: 0.401
Step: 36, Cost: 0.395
Step: 37, Cost: 0.388
Step: 38, Cost: 0.382
Step: 39, Cost: 0.377
Step: 40, Cost: 0.371
Step: 41, Cost: 0.365
Step: 42, Cost: 0.360
Step: 43, Cost: 0.355
Step: 44, Cost: 0.349
Step: 45, Cost: 0.344
Step: 46, Cost: 0.3

#### 6. 연습6

In [2]:
data = np.loadtxt('./data.csv', delimiter=',', unpack=True, dtype=np.float32)
x_data = np.transpose(data[:2])
y_data = np.transpose(data[2:])

In [3]:
global_step = tf.Variable(0, trainable=False, name='global_step')

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

with tf.name_scope('layer1'):
    W1 = tf.Variable(tf.random_uniform([2, 10], -1,1), name='W1')
    L1 = tf.nn.relu(tf.matmul(X, W1))
    
with tf.name_scope('layer2'):
    W2 = tf.Variable(tf.random_uniform([10, 20], -1,1), name='W2')
    L2 = tf.nn.relu(tf.matmul(L1, W2))
    
with tf.name_scope('output'):
    W3 = tf.Variable(tf.random_uniform([20, 3], -1,1), name='W3')
    model = tf.nn.softmax(tf.matmul(L2, W3))
    
with tf.name_scope('optimizer'):
    cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model), axis=1))
    optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
    train_op = optimizer.minimize(cost, global_step=global_step)
    init = tf.global_variables_initializer()
    tf.summary.scalar('cost', cost)

In [5]:
with tf.Session() as sess:
    saver = tf.train.Saver(tf.global_variables())
    ckpt = tf.train.get_checkpoint_state('./model')
    if ckpt and tf.train.checkpoint_exists(ckpt.model_checkpoint_path):
        saver.restore(sess, ckpt.model_checkpoint_path)
    else:
        sess.run(tf.global_variables_initializer())
    
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter('./logs', sess.graph)
    
    for step in range(100):
        sess.run(train_op, feed_dict={X: x_data, Y: y_data})
        if (1+step)%10 == 0:
            print(sess.run(cost, feed_dict={X: x_data, Y: y_data}))
        summary = sess.run(merged, feed_dict={X: x_data, Y: y_data})
        writer.add_summary(summary, global_step=sess.run(global_step))
            
    saver.save(sess, './model/cnn.ckpt', global_step=global_step)

INFO:tensorflow:Restoring parameters from ./model\cnn.ckpt-100
0.5497425
0.5496932
0.54965216
0.5496184
0.5495902
0.5495657
0.5495443
0.54952556
0.54950905
0.54949456
