In [135]:
import tensorflow as tf

In [181]:
sess = tf.Session()

In [143]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[8, 16], [2,3]])

with tf.Session() as sess:
    z = sess.run(tf.pow(x, y))
print(z)

[[  256 65536]
 [    9    27]]


In [178]:
z = tf.random_normal([3], mean=0., stddev=1., dtype=tf.float32, seed=20180906, name=None)

with tf.Session() as sess:
    n = sess.run(z)
print(n)

[0.3385797  0.88964117 1.7270286 ]


In [202]:
w = tf.random_uniform([3], minval=-1, maxval=1, dtype=tf.float32, seed=None)
print(sess.run(w))

[ 0.14660311  0.57919407 -0.40918136]


In [214]:
w.mean()

0.98508316

In [241]:
z = tf.random_normal([3,3], mean=0., stddev=1., dtype=tf.float32, seed=20180906, name=None)
a, b = sess.run([z, tf.reduce_mean(z, axis=0)])
print(a)
print(b)
print(a.mean(axis=0))

[[ 0.3385797   0.88964117  1.7270286 ]
 [ 1.5021957  -0.598586   -0.11976691]
 [ 0.7576737   1.3728415  -0.20659192]]
[0.8661497 0.5546322 0.4668899]
[0.8661497 0.5546322 0.4668899]


In [226]:
sess.run(tf.reduce_mean([1,2,123], axis=0))

42