In [1]:
import numpy as np

In [75]:
obj_func = lambda x: (x-3)**2

In [78]:
x = x0 = np.array([-40, 20, 10])
f = obj_func(x)

tol = 1e-10
for i in range(100):
    x_next = f[1]*f[2]/((f[0]-f[1])*(f[0]-f[2]))*x[0] + f[0]*f[2]/((f[1]-f[0])*(f[1]-f[2]))*x[1] + f[0]*f[1]/((f[2]-f[0])*(f[2]-f[1]))*x[2]
    x[:2] = x[1:]
    f[:2] = f[1:]
    x[2] = x_next
    f[2] = obj_func(x_next)
    print(x, f)
    if(f[2] < tol):
        break

print("Root: {}".format(x[2]))

[20 10  7] [289  49  18]
[10  7  5] [49 18  4]
[7 5 4] [18  4  1]
[5 4 3] [4 1 0]
Root: 3
