In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [128]:
def f(x):
    return x[0]**2 - 4*x[0] + x[1]**2 - x[1] - x[0]*x[1]
def g(x):
    return x[0]**2 - 4*x[1] + x[1]**2 - x[1] - x[0]*x[1]

In [126]:
def NelderMead(f, V):
    B, G, W = V[np.array([f(x) for x in V]).argsort()]
    M = (B+G)/2
    R = 2*M-W
    if f(R)<f(G):
        if f(B)<f(R):
            return np.asarray([B, G, R])
        else:
            E = 2*R-M
            if f(E)<f(B):
                return np.asarray([B, G, E])
            else:
                return np.asarray([B, G, R])
    else:
        if f(R)<f(W):
            return np.asarray([B, G, R])
        else:
            C = [(W+M)/2, (M+R)/2]
            C = C[np.argmin(np.array([f(C[0]), f(C[1])]))]
            if f(C)<f(W):
                return np.asarray([B, G, C])
            else:
                S = (W+B)/2
                return np.asarray([B, M, S])

In [129]:
# 초기화
V = np.array([[0.0, 0.8],
              [0.0, 0.0],
              [1.2, 0.0]])

print(V)
print("f(x) :", [g(x) for x in V])
for i in range(10):
    V = NelderMead(g, V)
    print(V)
    print("f(x) :", [g(x) for x in V])

[[0.  0.8]
 [0.  0. ]
 [1.2 0. ]]
f(x) : [-3.3600000000000003, 0.0, 1.44]
[[ 0.   0.8]
 [ 0.   0. ]
 [-1.2  0.8]]
f(x) : [-3.3600000000000003, 0.0, -0.9600000000000002]
[[ 0.   0.8]
 [-1.2  0.8]
 [-1.2  1.6]]
f(x) : [-3.3600000000000003, -0.9600000000000002, -2.08]
[[ 0.   0.8]
 [-1.2  1.6]
 [ 0.6  2. ]]
f(x) : [-3.3600000000000003, -2.08, -6.840000000000001]
[[0.6 2. ]
 [0.  0.8]
 [1.8 1.2]]
f(x) : [-6.840000000000001, -3.3600000000000003, -3.480000000000003]
[[0.6 2. ]
 [1.8 1.2]
 [2.4 2.4]]
f(x) : [-6.840000000000001, -3.480000000000003, -6.240000000000003]
[[0.6 2. ]
 [2.4 2.4]
 [1.2 3.2]]
f(x) : [-6.840000000000001, -6.240000000000003, -8.16]
[[1.2  3.2 ]
 [0.6  2.  ]
 [1.65 2.5 ]]
f(x) : [-8.16, -6.840000000000001, -7.652500000000001]
[[1.2  3.2 ]
 [1.65 2.5 ]
 [2.25 3.7 ]]
f(x) : [-8.16, -7.652500000000001, -8.0725]
[[1.2    3.2   ]
 [2.25   3.7   ]
 [1.6875 2.975 ]]
f(x) : [-8.16, -8.0725, -8.197031250000002]
[[1.6875   2.975   ]
 [1.2      3.2     ]
 [1.846875 3.39375 ]]
f(x) 