In [1]:
import numpy as np

In [72]:
def QR(A):
    
    # Variables
    n = len(A)
    a = []
    u = []
    e = []
    r = []

    # Q
    for i in range(n):
        a.append(A[:,i])
        tmp = np.zeros(n)
        for j in range(i):
            tmp += np.dot(a[i], e[j])*e[j] 
        u.append(a[i]-tmp)
        e.append(u[i]/np.sqrt(np.sum(u[i]**2)))

    Q = np.array(e).T

    # R
    for i in range(n):
        tmp = np.zeros(n)
        for j in range(i,n):
            tmp[j] = np.dot(a[j],e[i])
        r.append(tmp)

    R = np.array(r)
    
    return Q, R

In [75]:
# Unit Test
A = np.array([[1,2,0,2],
              [-2,4,-1,7],
              [2,6,2,0],
              [0,9,3,10]])

Q, R = QR(A)
print('-'*25,'Q','-'*25)
print(Q)
print('-'*25,'R','-'*25)
print(R)
print('-'*25,'A','-'*25)
print(np.matmul(Q,R))

------------------------- Q -------------------------
[[ 0.33333333  0.11561466 -0.58681925  0.72881089]
 [-0.66666667  0.46245865 -0.5461933  -0.20823168]
 [ 0.66666667  0.40465132 -0.25278368 -0.57263713]
 [ 0.          0.78039897  0.5416793   0.31234752]]
------------------------- R -------------------------
[[ 3.          2.          2.         -4.        ]
 [ 0.         11.53256259  2.68804091 11.2724296 ]
 [ 0.          0.          1.66566386  0.41980146]
 [ 0.          0.          0.          3.12347524]]
------------------------- A -------------------------
[[ 1.00000000e+00  2.00000000e+00 -9.95839721e-16  2.00000000e+00]
 [-2.00000000e+00  4.00000000e+00 -1.00000000e+00  7.00000000e+00]
 [ 2.00000000e+00  6.00000000e+00  2.00000000e+00 -5.81511308e-16]
 [ 0.00000000e+00  9.00000000e+00  3.00000000e+00  1.00000000e+01]]
