In [1]:
import numpy as np

In [4]:
r = 0.06
strikePrice = 1.10
stockPricePaths = np.array([
    [1.00,1.09,1.08,1.34],
    [1.00,1.16,1.26,1.54],
    [1.00,1.22,1.07,1.03],
    [1.00,0.93,0.97,0.92],
    [1.00,1.11,1.56,1.52],
    [1.00,0.76,0.77,0.9],
    [1.00,0.92,0.84,1.01],
    [1.00,0.88,1.22,1.34]])

In [101]:
strikePrice-stockPricePaths[:, t-1]>0

array([ True, False,  True,  True, False,  True,  True, False])

In [100]:
stoppingRule

array([False, False,  True,  True, False,  True,  True, False])

In [160]:
T = stockPricePaths.shape[1]-1

t = 3
# cashflow : t=3 시점에서 옵션의 가치
stoppingRule = strikePrice-stockPricePaths[:, t]>0
cashflow = np.where(stoppingRule,strikePrice-stockPricePaths[:, t],0)

# t=2 시점에서 행사할지 안 할지 고민하는 단계
# X : 행사할지 안 할지 고민할 때의 주식가격
# Y : 행사 안 하고 t=3 시점까지 가져갔을 때 옵션의 가치를 t=2 시점으로 할인
X = stockPricePaths[strikePrice-stockPricePaths[:, t-1]>0, t-1]
Y = cashflow[strikePrice-stockPricePaths[:, t-1]>0]*np.exp(-r)
M = np.c_[np.ones_like(X), X, X**2]
beta = np.linalg.inv(M.T@M)@M.T@Y

exercise = strikePrice-X
continuation = M@beta

np.fmax(exercise, continuation)

array([0.03674056, 0.04589834, 0.13      , 0.33      , 0.26      ])

In [ ]:
stoppingRule2 = strikePrice-stockPricePaths[:, t-1]>0
stoppingRule2[strikePrice-stockPricePaths[:, t-1]>0] = exercise>continuation
stoppingRule[stoppingRule2] = False
value = np.where(np.c_[stoppingRule2, stoppingRule], strikePrice-stockPricePaths[:, t-1:],0)@np.array([np.exp(-r), np.exp(-2*r)])
value

In [165]:
t = 2
X = stockPricePaths[strikePrice-stockPricePaths[:, t-1]>0, t-1]
Y = value[strikePrice-stockPricePaths[:, t-1]>0]

M = np.c_[np.ones_like(X), X, X**2]
beta = np.linalg.inv(M.T@M)@M.T@Y

exercise = strikePrice-X
continuation = M@beta

In [168]:
np.fmax(exercise, continuation)

array([0.01348511, 0.17      , 0.34      , 0.18      , 0.22      ])